image: node

stages:
  - build
  - test
  - deploy staging
  - deploy production
  - production test
  - cache

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/  
  policy: pull

update cache:
  stage: cache
  script:
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: push
  only:
    - schedules

build website:
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./public
  except:
    - schedules

test artifact:
  image: alpine
  stage: test
  cache: {}
  script:
    - grep "Gatsby" ./public/index.html
  except:
    - schedules

test website:
  stage: test
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"
  except:
    - schedules

deploy staging:
  stage: deploy staging
  environment:
    name: staging
    url: http://instazone-staging.surge.sh
  cache: {}
  script:
    - npm install --global surge
    - surge --project ./public --domain Browseshare-staging.surge.sh

deploy production:
  stage: deploy production
  environment:
    name: production
    url: http://instazone.surge.sh
  cache: {}
  script:
    - npm install --global surge
    - surge --project ./public --domain Browseshare.surge.sh

production test:
  image: alpine
  cache: {}
  stage: production test
  script:
    - apk add --no-cache curl
    - curl -s "https://instazone.surge.sh" | grep "Hi people"
  except:
    - schedules    